# Site settings
title: Be a Better Developer
email: 
description: "Practical notes on development by Sergey Barinov"
baseurl: "/BeBetterDeveloper"
url: "http://jelenabarinova.github.io" # the base hostname & protocol for your site
destination: ../gh-pages/
twitter_username: sergejusb
github_username: sergejusb
linkedin_username: sergejus
disqus_shortname: beabetterdeveloper

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 3
exclude: ["less","node_modules","package.json","README.md"]